---
title: Hastings Digital
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
locale: en-UK
title_separator: "-"
name: Adam Rifat
description: ''
url: http://hastings.digital
baseurl: 
gh_repo: 
teaser: 
words_per_minute: 200
comments:
  provider: 
  disqus:
    shortname: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
google_site_verification: 
bing_site_verification: 
alexa_site_verification: 
yandex_site_verification: 
twitter:
  username: adsrifat
facebook:
  username: 
  app_id: 
  publisher: 
og_image: 
social:
  type: 
  name: 
  links: 
analytics:
  provider: false
  google:
    tracking_id: 
google_ad_client: 
google_ad_slot: 
author:
  name: Adam Rifat
  avatar: bio-photo.jpg
  bio: I am an amazing person.
  location: Somewhere
  email: 
  uri: 
  bitbucket: 
  codepen: 
  dribbble: 
  flickr: 
  facebook: 
  foursquare: 
  github: 
  google_plus: 
  keybase: 
  instagram: 
  lastfm: 
  linkedin: 
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  tumblr: 
  twitter: 
  vine: 
  weibo: 
  xing: 
  youtube: 
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
gems:
- jekyll-paginate
whitelist:
- jekyll-paginate
categories:
  type: liquid
  path: "/categories/"
tags:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
